# Generated by Django 5.2.6 on 2025-10-04 03:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='サービス名')),
                ('image', models.ImageField(upload_to='services/', verbose_name='商品画像')),
                ('slug', models.SlugField(help_text='このサービスのユニークURL（例: reserve-system）', unique=True, verbose_name='URLスラッグ')),
                ('price', models.CharField(help_text='例: ¥50,000, ¥10,000~ など自由に入力できます', max_length=50, verbose_name='価格表記')),
                ('monthly_info', models.CharField(help_text='例: 運用保守費：月額１万円', max_length=100, verbose_name='月額情報など')),
                ('is_campaign_target', models.BooleanField(default=False, help_text='チェックを入れるとキャンペーン対象になります', verbose_name='キャンペーン対象')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='詳細ページ内容')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
