# Generated by Django 5.2.6 on 2025-10-04 04:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='content',
        ),
        migrations.AddField(
            model_name='service',
            name='description_rich',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='詳しい説明（画像・テキスト）'),
        ),
        migrations.AddField(
            model_name='service',
            name='flow_rich',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='導入の流れ（画像・テキスト）'),
        ),
        migrations.AddField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/main_images/', verbose_name='（詳細ページ用）メイン画像'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/thumbnails/', verbose_name='（一覧用）商品画像'),
        ),
    ]
