# Generated by Django 5.2.6 on 2025-10-05 02:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_content_service_description_rich_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('client_name', models.CharField(blank=True, help_text='公開可能な場合のみ入力', max_length=100, verbose_name='クライアント名')),
                ('industry', models.CharField(choices=[('restaurant', '飲食業'), ('retail', '小売業'), ('medical', '医療・介護'), ('education', '教育'), ('manufacturing', '製造業'), ('consulting', 'コンサルティング'), ('real_estate', '不動産'), ('finance', '金融'), ('other', 'その他')], max_length=50, verbose_name='業界')),
                ('project_type', models.CharField(choices=[('website', 'Webサイト制作'), ('system', 'システム開発'), ('ec', 'ECサイト構築'), ('reserve', '予約システム'), ('dx', 'DX支援'), ('support', 'IT伴走サポート')], max_length=50, verbose_name='プロジェクト種別')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('duration_months', models.PositiveIntegerField(help_text='例: 3ヶ月なら3と入力', verbose_name='開発期間（月数）')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='メイン画像')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='achievements/before/', verbose_name='Before画像')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='achievements/after/', verbose_name='After画像')),
                ('description', ckeditor.fields.RichTextField(help_text='課題や要求事項について', verbose_name='プロジェクト概要')),
                ('solution', ckeditor.fields.RichTextField(help_text='どのような解決策を提供したか', verbose_name='提供ソリューション')),
                ('results', ckeditor.fields.RichTextField(help_text='具体的な数値や改善効果', verbose_name='成果・効果')),
                ('technologies', models.TextField(help_text='Python, Django, React, AWS など（カンマ区切り）', verbose_name='使用技術')),
                ('performance_improvement', models.CharField(blank=True, help_text='例: ページ速度50%向上', max_length=100, verbose_name='性能改善')),
                ('cost_reduction', models.CharField(blank=True, help_text='例: 運用コスト30%削減', max_length=100, verbose_name='コスト削減')),
                ('sales_improvement', models.CharField(blank=True, help_text='例: 売上20%向上', max_length=100, verbose_name='売上向上')),
                ('client_feedback', models.TextField(blank=True, help_text='お客様からのコメント', verbose_name='クライアントの声')),
                ('satisfaction_score', models.PositiveIntegerField(default=5, help_text='1-5段階評価', verbose_name='満足度')),
                ('is_featured', models.BooleanField(default=False, help_text='トップページなどで優先表示', verbose_name='注目実績')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '実績',
                'verbose_name_plural': '実績一覧',
                'ordering': ['-end_date', '-start_date', 'display_order'],
            },
        ),
    ]
