# Generated by Django 5.2.6 on 2025-10-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_achievement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.AddField(
            model_name='service',
            name='campaign_price',
            field=models.CharField(blank=True, help_text='キャンペーン対象の場合の特別価格', max_length=50, null=True, verbose_name='キャンペーン価格'),
        ),
    ]
